module.exports = {
  cli: [
    {
      type: "autogenerated",
      dirName: "cli",
    },
  ],
  internals: [
    {
      type: "autogenerated",
      dirName: "internals",
    },
  ],
  intro: [
    {
      type: "autogenerated",
      dirName: "intro",
    },
  ],
  language: [
    {
      type: "autogenerated",
      dirName: "language",
    },
  ],
};
